// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type AccountType string

const (
	AccountFacebook      AccountType = "facebook"
	AccountLdap          AccountType = "ldap"
	AccountNis           AccountType = "nis"
	AccountOpenid        AccountType = "openid"
	AccountRadius        AccountType = "radius"
	AccountSkype         AccountType = "skype"
	AccountTacacs        AccountType = "tacacs"
	AccountTwitter       AccountType = "twitter"
	AccountUnix          AccountType = "unix"
	AccountWindowsLocal  AccountType = "windows-local"
	AccountWindowsDomain AccountType = "windows-domain"
)
