// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type AttackMotivation string

const (
	AttackAccidental           AttackMotivation = "accidental"
	AttackCoercion             AttackMotivation = "coercion"
	AttackDominance            AttackMotivation = "dominance"
	AttackIdeology             AttackMotivation = "ideology"
	AttackNotoriety            AttackMotivation = "notoriety"
	AttackOrganizationalGain   AttackMotivation = "organizational-gain"
	AttackPersonalGain         AttackMotivation = "personal-gain"
	AttackPersonalSatisfaction AttackMotivation = "personal-satisfaction"
	AttackRevenge              AttackMotivation = "revenge"
	AttackUnpredictable        AttackMotivation = "unpredictable"
)
