// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type AttackResourceLevel string

const (
	AttackResourceIndividual   AttackResourceLevel = "individual"
	AttackResourceClub         AttackResourceLevel = "club"
	AttackResourceContest      AttackResourceLevel = "contest"
	AttackResourceTeam         AttackResourceLevel = "team"
	AttackResourceOrganization AttackResourceLevel = "organization"
	AttackResourceGovernment   AttackResourceLevel = "government"
)
