// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type CourseOfActionType string

const (
	CourseOfActionTextualTextPlain CourseOfActionType = "textual:text/plain"
	CourseOfActionTextualTextHtml  CourseOfActionType = "textual:text/html"
	CourseOfActionTextualTextMd    CourseOfActionType = "textual:text/md"
	CourseOfActionTextualPdf       CourseOfActionType = "textual:pdf"
)
