// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type EncryptionAlgorithm string

const (
	EncryptionAES256GCM         EncryptionAlgorithm = "AES-256-GCM"
	EncryptionChaCha20Poly1305  EncryptionAlgorithm = "ChaCha20-Poly1305"
	EncryptionMimeTypeIndicated EncryptionAlgorithm = "mime-type-indicated"
)
