// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type GroupingContext string

const (
	GroupingSuspiciousActivity GroupingContext = "suspicious-activity"
	GroupingMalwareAnalysis    GroupingContext = "malware-analysis"
	GroupingUnspecified        GroupingContext = "unspecified"
)
