// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type HashingAlgorithm string

const (
	HashingMD5     HashingAlgorithm = "MD5"
	HashingSHA1    HashingAlgorithm = "SHA-1"
	HashingSHA256  HashingAlgorithm = "SHA-256"
	HashingSHA512  HashingAlgorithm = "SHA-512"
	HashingSHA3256 HashingAlgorithm = "SHA3-256"
	HashingSHA3512 HashingAlgorithm = "SHA3-512"
	HashingSSDEEP  HashingAlgorithm = "SSDEEP"
)
