// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type IdentityClass string

const (
	IdentityIndividual   IdentityClass = "individual"
	IdentityGroup        IdentityClass = "group"
	IdentitySystem       IdentityClass = "system"
	IdentityOrganization IdentityClass = "organization"
	IdentityClassClass   IdentityClass = "class"
	IdentityUnknown      IdentityClass = "unknown"
)
