// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type ImplementationLanguage string

const (
	ImplementationApplescript ImplementationLanguage = "applescript"
	ImplementationBash        ImplementationLanguage = "bash"
	ImplementationC           ImplementationLanguage = "c"
	ImplementationCpp         ImplementationLanguage = "c++"
	ImplementationCsharp      ImplementationLanguage = "c#"
	ImplementationGo          ImplementationLanguage = "go"
	ImplementationJava        ImplementationLanguage = "java"
	ImplementationJavascript  ImplementationLanguage = "javascript"
	ImplementationLua         ImplementationLanguage = "lua"
	ImplementationObjectiveC  ImplementationLanguage = "objective-c"
	ImplementationPerl        ImplementationLanguage = "perl"
	ImplementationPhp         ImplementationLanguage = "php"
	ImplementationPowershell  ImplementationLanguage = "powershell"
	ImplementationPython      ImplementationLanguage = "python"
	ImplementationRuby        ImplementationLanguage = "ruby"
	ImplementationScala       ImplementationLanguage = "scala"
	ImplementationSwift       ImplementationLanguage = "swift"
	ImplementationTypescript  ImplementationLanguage = "typescript"
	ImplementationVisualBasic ImplementationLanguage = "visual-basic"
	ImplementationX8632       ImplementationLanguage = "x86-32"
	ImplementationX8664       ImplementationLanguage = "x86-64"
)
