// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type IndicatorType string

const (
	IndicatorAnomalousActivity IndicatorType = "anomalous-activity"
	IndicatorAnonymization     IndicatorType = "anonymization"
	IndicatorBenign            IndicatorType = "benign"
	IndicatorCompromised       IndicatorType = "compromised"
	IndicatorMaliciousActivity IndicatorType = "malicious-activity"
	IndicatorAttribution       IndicatorType = "attribution"
	IndicatorUnknown           IndicatorType = "unknown"
)
