// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type IndustrySector string

const (
	IndustryAgriculture              IndustrySector = "agriculture"
	IndustryAerospace                IndustrySector = "aerospace"
	IndustryAutomotive               IndustrySector = "automotive"
	IndustryChemical                 IndustrySector = "chemical"
	IndustryCommercial               IndustrySector = "commercial"
	IndustryCommunications           IndustrySector = "communications"
	IndustryConstruction             IndustrySector = "construction"
	IndustryDefense                  IndustrySector = "defense"
	IndustryEducation                IndustrySector = "education"
	IndustryEnergy                   IndustrySector = "energy"
	IndustryEntertainment            IndustrySector = "entertainment"
	IndustryFinancialServices        IndustrySector = "financial-services"
	IndustryGovernment               IndustrySector = "government"
	IndustryEmergencyServices        IndustrySector = "emergency-services"
	IndustryGovernmentNational       IndustrySector = "government-national"
	IndustryGovernmentRegional       IndustrySector = "government-regional"
	IndustryGovernmentLocal          IndustrySector = "government-local"
	IndustryGovernmentPublicServices IndustrySector = "government-public-services"
	IndustryHealthcare               IndustrySector = "healthcare"
	IndustryHospitalityLeisure       IndustrySector = "hospitality-leisure"
	IndustryInfrastructure           IndustrySector = "infrastructure"
	IndustryDams                     IndustrySector = "dams"
	IndustryNuclear                  IndustrySector = "nuclear"
	IndustryWater                    IndustrySector = "water"
	IndustryInsurance                IndustrySector = "insurance"
	IndustryManufacturing            IndustrySector = "manufacturing"
	IndustryMining                   IndustrySector = "mining"
	IndustryNonProfit                IndustrySector = "non-profit"
	IndustryPharmaceuticals          IndustrySector = "pharmaceuticals"
	IndustryRetail                   IndustrySector = "retail"
	IndustryTechnology               IndustrySector = "technology"
	IndustryTelecommunications       IndustrySector = "telecommunications"
	IndustryTransportation           IndustrySector = "transportation"
	IndustryUtilities                IndustrySector = "utilities"
)
