// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type InfrastructureType string

const (
	InfrastructureAmplification      InfrastructureType = "amplification"
	InfrastructureAnonymization      InfrastructureType = "anonymization"
	InfrastructureBotnet             InfrastructureType = "botnet"
	InfrastructureCommandAndControl  InfrastructureType = "command-and-control"
	InfrastructureExfiltration       InfrastructureType = "exfiltration"
	InfrastructureHostingMalware     InfrastructureType = "hosting-malware"
	InfrastructureHostingTargetLists InfrastructureType = "hosting-target-lists"
	InfrastructurePhishing           InfrastructureType = "phishing"
	InfrastructureReconnaissance     InfrastructureType = "reconnaissance"
	InfrastructureStaging            InfrastructureType = "staging"
	InfrastructureUnknown            InfrastructureType = "unknown"
)
