// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type NetworkSocketType string

const (
	NetworkSocketSOCK_STREAM    NetworkSocketType = "SOCK_STREAM"
	NetworkSocketSOCK_DGRAM     NetworkSocketType = "SOCK_DGRAM"
	NetworkSocketSOCK_RAW       NetworkSocketType = "SOCK_RAW"
	NetworkSocketSOCK_RDM       NetworkSocketType = "SOCK_RDM"
	NetworkSocketSOCK_SEQPACKET NetworkSocketType = "SOCK_SEQPACKET"
)
