// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type NetworkSocketAddressFamily string

const (
	NetworkSocketAddressAF_UNSPEC    NetworkSocketAddressFamily = "AF_UNSPEC"
	NetworkSocketAddressAF_INET      NetworkSocketAddressFamily = "AF_INET"
	NetworkSocketAddressAF_IPX       NetworkSocketAddressFamily = "AF_IPX"
	NetworkSocketAddressAF_APPLETALK NetworkSocketAddressFamily = "AF_APPLETALK"
	NetworkSocketAddressAF_NETBIOS   NetworkSocketAddressFamily = "AF_NETBIOS"
	NetworkSocketAddressAF_INET6     NetworkSocketAddressFamily = "AF_INET6"
	NetworkSocketAddressAF_IRDA      NetworkSocketAddressFamily = "AF_IRDA"
	NetworkSocketAddressAF_BTH       NetworkSocketAddressFamily = "AF_BTH"
)
