// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type Opinion string

const (
	OpinionStronglyDisagree Opinion = "strongly-disagree"
	OpinionDisagree         Opinion = "disagree"
	OpinionNeutral          Opinion = "neutral"
	OpinionAgree            Opinion = "agree"
	OpinionStronglyAgree    Opinion = "strongly-agree"
)
