// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type ProcessorArchitecture string

const (
	ProcessorAlpha   ProcessorArchitecture = "alpha"
	ProcessorArm     ProcessorArchitecture = "arm"
	ProcessorIa64    ProcessorArchitecture = "ia-64"
	ProcessorMips    ProcessorArchitecture = "mips"
	ProcessorPowerpc ProcessorArchitecture = "powerpc"
	ProcessorSparc   ProcessorArchitecture = "sparc"
	ProcessorX86     ProcessorArchitecture = "x86"
	ProcessorX8664   ProcessorArchitecture = "x86-64"
)
