// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type Region string

const (
	RegionAfrica                Region = "africa"
	RegionEasternAfrica         Region = "eastern-africa"
	RegionMiddleAfrica          Region = "middle-africa"
	RegionNorthernAfrica        Region = "northern-africa"
	RegionSouthernAfrica        Region = "southern-africa"
	RegionWesternAfrica         Region = "western-africa"
	RegionAmericas              Region = "americas"
	RegionLatinAmericaCaribbean Region = "latin-america-caribbean"
	RegionSouthAmerica          Region = "south-america"
	RegionCaribbean             Region = "caribbean"
	RegionCentralAmerica        Region = "central-america"
	RegionNorthernAmerica       Region = "northern-america"
	RegionAsia                  Region = "asia"
	RegionCentralAsia           Region = "central-asia"
	RegionEasternAsia           Region = "eastern-asia"
	RegionSouthernAsia          Region = "southern-asia"
	RegionSouthEasternAsia      Region = "south-eastern-asia"
	RegionWesternAsia           Region = "western-asia"
	RegionEurope                Region = "europe"
	RegionEasternEurope         Region = "eastern-europe"
	RegionNorthernEurope        Region = "northern-europe"
	RegionSouthernEurope        Region = "southern-europe"
	RegionWesternEurope         Region = "western-europe"
	RegionOceania               Region = "oceania"
	RegionAntarctica            Region = "antarctica"
	RegionAustraliaNewZealand   Region = "australia-new-zealand"
	RegionMelanesia             Region = "melanesia"
	RegionMicronesia            Region = "micronesia"
	RegionPolynesia             Region = "polynesia"
)
