// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type ReportType string

const (
	ReportAttackPattern ReportType = "attack-pattern"
	ReportCampaign      ReportType = "campaign"
	ReportIdentity      ReportType = "identity"
	ReportIndicator     ReportType = "indicator"
	ReportIntrusionSet  ReportType = "intrusion-set"
	ReportMalware       ReportType = "malware"
	ReportObservedData  ReportType = "observed-data"
	ReportThreatActor   ReportType = "threat-actor"
	ReportThreatReport  ReportType = "threat-report"
	ReportTool          ReportType = "tool"
	ReportVulnerability ReportType = "vulnerability"
)
