// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type ThreatActorRole string

const (
	ThreatActorAgent                   ThreatActorRole = "agent"
	ThreatActorDirector                ThreatActorRole = "director"
	ThreatActorIndependent             ThreatActorRole = "independent"
	ThreatActorInfrastructureArchitect ThreatActorRole = "infrastructure-architect"
	ThreatActorInfrastructureOperator  ThreatActorRole = "infrastructure-operator"
	ThreatActorMalwareAuthor           ThreatActorRole = "malware-author"
	ThreatActorSponsor                 ThreatActorRole = "sponsor"
)
