// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type ThreatActorType string

const (
	ThreatActorActivist           ThreatActorType = "activist"
	ThreatActorCompetitor         ThreatActorType = "competitor"
	ThreatActorCrimeSyndicate     ThreatActorType = "crime-syndicate"
	ThreatActorCriminal           ThreatActorType = "criminal"
	ThreatActorHacker             ThreatActorType = "hacker"
	ThreatActorInsiderAccidental  ThreatActorType = "insider-accidental"
	ThreatActorInsiderDisgruntled ThreatActorType = "insider-disgruntled"
	ThreatActorNationState        ThreatActorType = "nation-state"
	ThreatActorSensationalist     ThreatActorType = "sensationalist"
	ThreatActorSpy                ThreatActorType = "spy"
	ThreatActorTerrorist          ThreatActorType = "terrorist"
	ThreatActorUnknown            ThreatActorType = "unknown"
)
