// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type ThreatActorSophistication string

const (
	ThreatActorNone         ThreatActorSophistication = "none"
	ThreatActorMinimal      ThreatActorSophistication = "minimal"
	ThreatActorIntermediate ThreatActorSophistication = "intermediate"
	ThreatActorAdvanced     ThreatActorSophistication = "advanced"
	ThreatActorExpert       ThreatActorSophistication = "expert"
	ThreatActorInnovator    ThreatActorSophistication = "innovator"
	ThreatActorStrategic    ThreatActorSophistication = "strategic"
)
