// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type ToolType string

const (
	ToolDenialOfService        ToolType = "denial-of-service"
	ToolExploitation           ToolType = "exploitation"
	ToolInformationGathering   ToolType = "information-gathering"
	ToolNetworkCapture         ToolType = "network-capture"
	ToolCredentialExploitation ToolType = "credential-exploitation"
	ToolRemoteAccess           ToolType = "remote-access"
	ToolVulnerabilityScanning  ToolType = "vulnerability-scanning"
	ToolUnknown                ToolType = "unknown"
)
