// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type WindowsPebinaryType string

const (
	WindowsPebinaryDll WindowsPebinaryType = "dll"
	WindowsPebinaryExe WindowsPebinaryType = "exe"
	WindowsPebinarySys WindowsPebinaryType = "sys"
)
