// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type WindowsServiceType string

const (
	WindowsServiceSERVICE_KERNEL_DRIVER       WindowsServiceType = "SERVICE_KERNEL_DRIVER"
	WindowsServiceSERVICE_FILE_SYSTEM_DRIVER  WindowsServiceType = "SERVICE_FILE_SYSTEM_DRIVER"
	WindowsServiceSERVICE_WIN32_OWN_PROCESS   WindowsServiceType = "SERVICE_WIN32_OWN_PROCESS"
	WindowsServiceSERVICE_WIN32_SHARE_PROCESS WindowsServiceType = "SERVICE_WIN32_SHARE_PROCESS"
)
