// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type WindowsRegistryDatatype string

const (
	WindowsRegistryREG_NONE                       WindowsRegistryDatatype = "REG_NONE"
	WindowsRegistryREG_SZ                         WindowsRegistryDatatype = "REG_SZ"
	WindowsRegistryREG_EXPAND_SZ                  WindowsRegistryDatatype = "REG_EXPAND_SZ"
	WindowsRegistryREG_BINARY                     WindowsRegistryDatatype = "REG_BINARY"
	WindowsRegistryREG_DWORD                      WindowsRegistryDatatype = "REG_DWORD"
	WindowsRegistryREG_DWORD_BIG_ENDIAN           WindowsRegistryDatatype = "REG_DWORD_BIG_ENDIAN"
	WindowsRegistryREG_DWORD_LITTLE_ENDIAN        WindowsRegistryDatatype = "REG_DWORD_LITTLE_ENDIAN"
	WindowsRegistryREG_LINK                       WindowsRegistryDatatype = "REG_LINK"
	WindowsRegistryREG_MULTI_SZ                   WindowsRegistryDatatype = "REG_MULTI_SZ"
	WindowsRegistryREG_RESOURCE_LIST              WindowsRegistryDatatype = "REG_RESOURCE_LIST"
	WindowsRegistryREG_FULL_RESOURCE_DESCRIPTION  WindowsRegistryDatatype = "REG_FULL_RESOURCE_DESCRIPTION"
	WindowsRegistryREG_RESOURCE_REQUIREMENTS_LIST WindowsRegistryDatatype = "REG_RESOURCE_REQUIREMENTS_LIST"
	WindowsRegistryREG_QWORD                      WindowsRegistryDatatype = "REG_QWORD"
	WindowsRegistryREG_INVALID_TYPE               WindowsRegistryDatatype = "REG_INVALID_TYPE"
)
