// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type WindowsIntegrityLevel string

const (
	WindowsIntegrityLow    WindowsIntegrityLevel = "low"
	WindowsIntegrityMedium WindowsIntegrityLevel = "medium"
	WindowsIntegrityHigh   WindowsIntegrityLevel = "high"
	WindowsIntegritySystem WindowsIntegrityLevel = "system"
)
