// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type WindowsServiceStatus string

const (
	WindowsServiceSERVICE_CONTINUE_PENDING WindowsServiceStatus = "SERVICE_CONTINUE_PENDING"
	WindowsServiceSERVICE_PAUSE_PENDING    WindowsServiceStatus = "SERVICE_PAUSE_PENDING"
	WindowsServiceSERVICE_PAUSED           WindowsServiceStatus = "SERVICE_PAUSED"
	WindowsServiceSERVICE_RUNNING          WindowsServiceStatus = "SERVICE_RUNNING"
	WindowsServiceSERVICE_START_PENDING    WindowsServiceStatus = "SERVICE_START_PENDING"
	WindowsServiceSERVICE_STOP_PENDING     WindowsServiceStatus = "SERVICE_STOP_PENDING"
	WindowsServiceSERVICE_STOPPED          WindowsServiceStatus = "SERVICE_STOPPED"
)
