// THIS FILE IS AUTOGENERATED BY generate_vocabs.py

package vocabs

type WindowsServiceStartType string

const (
	WindowsServiceStartSERVICE_AUTO_START   WindowsServiceStartType = "SERVICE_AUTO_START"
	WindowsServiceStartSERVICE_BOOT_START   WindowsServiceStartType = "SERVICE_BOOT_START"
	WindowsServiceStartSERVICE_DEMAND_START WindowsServiceStartType = "SERVICE_DEMAND_START"
	WindowsServiceStartSERVICE_DISABLED     WindowsServiceStartType = "SERVICE_DISABLED"
	WindowsServiceStartSERVICE_SYSTEM_ALERT WindowsServiceStartType = "SERVICE_SYSTEM_ALERT"
)
